# Generated by Django 3.0.8 on 2020-07-06 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to=upload_file.models.upload_file_storage)),
                ('separator', models.CharField(default=',', max_length=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Upload File',
            },
        ),
    ]
